name: Perform checks

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: |
        docker build -t makocchi/actions-k8s-manifests-validate-conftest:${{ github.sha }} .
    - name: Run check
      run: |
        docker run -v ${PWD}/example:/example makocchi/actions-k8s-manifests-validate-conftest:${{ github.sha }} "/example" "stdout" "/policy" "false" "" "false" ""
